# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradingRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarksRubricAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks', models.PositiveSmallIntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisioned_rubrics.Attempt')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisioned_rubrics.GradingRevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('q_text', models.TextField(help_text='Text for the question that the student sees')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('max_marks', models.PositiveSmallIntegerField(default=10)),
                ('grading_guidelines', models.TextField(help_text='Guidelines on how to grade the rubric')),
                ('is_leaf', models.BooleanField(default=False, help_text='Is the Rubric a leaf? Only leaf rubrics get graded')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dest_rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='revisioned_rubrics.Rubric')),
                ('src_rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='revisioned_rubrics.Rubric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rubricedge',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisioned_rubrics.RubricTree'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisioned_rubrics.RubricTree'),
        ),
        migrations.AddField(
            model_name='question',
            name='rubric_tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisioned_rubrics.RubricTree'),
        ),
        migrations.AddField(
            model_name='marksrubricattempt',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisioned_rubrics.Rubric'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisioned_rubrics.Question'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='rubric_tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisioned_rubrics.RubricTree'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisioned_rubrics.Student'),
        ),
    ]
